# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ίχίχίχίχ
email: xu509@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  lalalallallallalalalalalallalalalalalalalllllalalalalalalalalalalalallalala
baseurl: "test" # the subpath of your site, e.g. /blog
url: "blog.lmxnx.com" # the base hostname & protocol for your site
twitter_username: xu509
github_username:  xu509

# Build settings
markdown: kramdown
