# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Alan's blog
email: xu509@outlook.com
description: > # Let's enjoy tech!
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.lmxnx.com" # the base hostname & protocol for your site
# twitter_username: xu509
github_username:  xu509

# Build settings
markdown: kramdown
